[package]
org = "xlibb"
name = "pipeline"
version = "@toml.version@"
authors = ["xlibb"]
keywords = ["pipeline", "handler", "replay", "processor", "destination", "store"]
repository = "https://github.com/xlibb/module-pipeline"
license = ["Apache-2.0"]
distribution = "2201.12.0"
